"""
FLO-303: Boss → Floki communication channel.

Hermano writes directives in `data/boss_notes.json`. On each Floki cycle the
active notes are injected into the user message as a <boss_notes> block near
the top — framed as manager directives, not data. Floki echoes the IDs he
has read in an `"acknowledged_boss_notes": [...]` field; parser stamps the
timestamps back and dismisses one-shots.

Non-blocking everywhere: missing file / malformed JSON / empty list → no
injection. If Floki forgets to ack, notes keep appearing until he does or
they expire. Acknowledgement means "I read it," not "I complied."

Schema (data/boss_notes.json):
  {
    "notes": [
      {
        "id":             "2026-04-14-01",      // Hermano sets or auto-generated by add_note()
        "text":           "D1 chart is operational since Apr 13. Use it.",
        "created_at":     "2026-04-14T18:00:00Z",
        "expires_at":     "2026-04-15T18:00:00Z" | null,  // null = permanent
        "requires_ack":   true,                  // false = informational, no ack prompt
        "ack_dismisses":  false,                 // true = one-shot; removed after first ack
        "acknowledged_at": null                  // ISO timestamp once Floki acks
      }
    ]
  }

Module-level functions are all safe to call at import time — no I/O on import.
"""
import json
import os
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from logger import log
from tz_utils import utc_iso, utc_now


_NOTES_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "data", "boss_notes.json"
)
_DEFAULT_EXPIRY_HOURS = 24


def _load() -> Dict[str, Any]:
    try:
        if not os.path.exists(_NOTES_PATH):
            return {"notes": []}
        with open(_NOTES_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, dict) or not isinstance(data.get("notes"), list):
            log.debug("boss_notes: malformed file, returning empty")
            return {"notes": []}
        return data
    except Exception as e:
        log.debug(f"boss_notes: load failed (ignored): {e}")
        return {"notes": []}


def _save(data: Dict[str, Any]) -> bool:
    try:
        os.makedirs(os.path.dirname(_NOTES_PATH), exist_ok=True)
        tmp = _NOTES_PATH + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp, _NOTES_PATH)
        return True
    except Exception as e:
        log.debug(f"boss_notes: save failed (ignored): {e}")
        return False


def get_active_notes() -> List[Dict[str, Any]]:
    """Return notes that should appear in trigger_context right now.

    A note is active when:
      - expires_at is None (permanent) OR expires_at > now
      - AND it is NOT already (acknowledged AND ack_dismisses=True)
        — that case is cleaned out by record_acknowledgements() anyway,
          but the filter here is defensive.
    """
    data = _load()
    now = utc_now()
    active: List[Dict[str, Any]] = []
    for n in data.get("notes", []):
        if not isinstance(n, dict):
            continue
        exp = n.get("expires_at")
        if exp:
            try:
                exp_dt = datetime.fromisoformat(str(exp).replace("Z", "+00:00"))
                if exp_dt.tzinfo is None:
                    exp_dt = exp_dt.replace(tzinfo=timezone.utc)
                if exp_dt <= now:
                    continue
            except Exception:
                # Malformed timestamp — treat as permanent rather than silently drop.
                pass
        if n.get("acknowledged_at") and n.get("ack_dismisses"):
            continue
        active.append(n)
    return active


def render_block(notes: Optional[List[Dict[str, Any]]] = None) -> str:
    """Render active notes as a <boss_notes> XML block for prompt injection.

    Returns empty string when there are no active notes → caller can always
    concatenate unconditionally.
    """
    if notes is None:
        notes = get_active_notes()
    if not notes:
        return ""

    lines: List[str] = [
        "<boss_notes>",
        "From Hermano (your manager) — treat these as directives, not data. "
        "Compliance matters more than agreement; if you disagree, acknowledge "
        "the note and explain your deviation in reasoning.",
        "",
    ]
    for n in notes:
        nid = n.get("id", "?")
        created = n.get("created_at", "?")
        exp = n.get("expires_at")
        req_ack = n.get("requires_ack", True)
        meta = [f"id={nid}", f"created {created}"]
        meta.append(f"expires {exp}" if exp else "permanent")
        if n.get("acknowledged_at"):
            meta.append(f"acked {n['acknowledged_at']}")
        elif req_ack:
            meta.append("ACK REQUIRED")
        lines.append(f"[{' | '.join(meta)}]")
        lines.append(str(n.get("text", "")).strip())
        lines.append("")

    lines.append(
        'In your JSON response, include:  '
        '"acknowledged_boss_notes": ["<id>", ...]  '
        "— list every note ID above that you have READ and understood this cycle. "
        "Acknowledgement is separate from compliance."
    )
    lines.append("</boss_notes>")
    return "\n".join(lines)


def record_acknowledgements(ack_ids: List[str]) -> None:
    """Stamp notes as acknowledged; remove those with ack_dismisses=True.

    Logs a single FLOKI_BOSS_ACK line summarising acked / dismissed / pending IDs.
    Non-blocking on any failure.
    """
    if not ack_ids:
        return
    try:
        data = _load()
        now_iso = utc_iso()
        touched: List[str] = []
        dismissed: List[str] = []
        kept: List[Dict[str, Any]] = []
        ack_set = {str(i).strip() for i in ack_ids if str(i).strip()}

        for n in data.get("notes", []):
            if not isinstance(n, dict):
                kept.append(n)
                continue
            if str(n.get("id", "")) in ack_set:
                # First-time ack gets the timestamp; subsequent acks leave it alone.
                if not n.get("acknowledged_at"):
                    n["acknowledged_at"] = now_iso
                touched.append(str(n.get("id")))
                if n.get("ack_dismisses"):
                    dismissed.append(str(n.get("id")))
                    continue  # drop from kept list
            kept.append(n)

        data["notes"] = kept
        _save(data)

        pending = [
            str(n.get("id"))
            for n in kept
            if n.get("requires_ack", True) and not n.get("acknowledged_at")
        ]
        if touched or dismissed:
            log.info(
                f"FLOKI_BOSS_ACK | acked={touched} | "
                f"dismissed={dismissed} | pending={pending}"
            )
    except Exception as e:
        log.debug(f"boss_notes: ack recording failed (ignored): {e}")


def add_note(
    text: str,
    expires_hours: Optional[int] = _DEFAULT_EXPIRY_HOURS,
    permanent: bool = False,
    requires_ack: bool = True,
    ack_dismisses: bool = False,
    note_id: Optional[str] = None,
) -> str:
    """Append a note and persist. Returns the note id.

    Helper for manual file-editing OR a future CLI wrapper. Auto-generates
    YYYY-MM-DD-NN ids keyed off the current UTC date if none supplied.
    """
    data = _load()
    now = utc_now()
    if not note_id:
        date_str = now.strftime("%Y-%m-%d")
        same_day = [n for n in data.get("notes", []) if str(n.get("id", "")).startswith(date_str)]
        note_id = f"{date_str}-{len(same_day) + 1:02d}"
    if permanent or expires_hours is None:
        expires_at: Optional[str] = None
    else:
        expires_at = utc_iso(now + timedelta(hours=int(expires_hours)))
    note = {
        "id": note_id,
        "text": str(text).strip(),
        "created_at": utc_iso(now),
        "expires_at": expires_at,
        "requires_ack": bool(requires_ack),
        "ack_dismisses": bool(ack_dismisses),
        "acknowledged_at": None,
    }
    data.setdefault("notes", []).append(note)
    _save(data)
    return note_id
